### ISSUE TITLE
Using .Result causes the LINQ statement to hang indefinitely

### ISSUE THREAD

**Issue by lbowers** [JoeMayo/LinqToTwitter#13]
I'm probably not using LinqToTwitter quite as intended, but the use of .Result in the following statement causes the linq statement (further down) to hang indefinitely:

        public IndexModel()
        {
            Feed = GetFeed().Result;
        }
        
private static async Task<API.Feed> GetFeed()
        {
            return await API.Get();
        }

Basically, I'm trying to retrieve the Twitter feed in my models constructor (ASP.Net MVC), and I want it to work synchronously (hence the .Result). I need the Twitter feed to be available in the model, so that I can render the tweets in the view. Not quite sure how I'm supposed to do this asynchronously. Anyway...

Here's my linq:

                    List<Status> tweets = await
                        (from tweet in twitterCtx.Status
                         where tweet.Type == StatusType.User &&
                               tweet.ScreenName == "..." &&
                               tweet.SinceID == feed.SinceId &&
                               tweet.Count == 5
                         select tweet)
                            .ToListAsync();

Shouldn't this work? I've used the .Result approach elsewhere, and it's worked as expected.

**Comment by JoeMayo** [comment]
Hi Leigh,

Calls to Wait() and Result are blocking and can cause problems like this. I'm guessing that the reason you're loading Feed in the constructor is because you know that every action in that controller will need it. If that isn't true, then it might be a better design to load Feed on-demand. For that reason, and to work around the blocked thread problem, I would do something like this:

1. Create an async GetFeedAsync method.
2. Inside of GetFeedAsync, check the Feed property to see if it has values.
3. If so, return Feed.
4. If not, perform the LINQ to Twitter query, load Feed, and return Feed.
5. await GetFeedAsync in the action(s) that use it.

Joe

**Comment by lbowers** [comment]
Hi Joe,

Thanks for the amazingly quick and detailed response! I'll give that a whirl...
