### ISSUE TITLE
LinqtoTwitter v5.0.0 installation error

### ISSUE THREAD

**Issue by ErenSongur** [JoeMayo/LinqToTwitter#143]
Greetings,

I tried to add LinqtoTwitter v5.0.0 to my web api project and I get the following error:
Could not install package 'linqtotwitter 5.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Thank you for your help

With regards,

Eren

**Comment by JoeMayo** [comment]
Hi Eren,

The LinqToTwitter.AspNet.dll assembly is build on .NET v4.6.1. Are you able to upgrade your ASP.NET project to v4.6.1?

[@JoeMayo](https://twitter.com/joemayo)

**Comment by JoeMayo** [comment]
Eren,

I took a quick look at this and think it will be possible. The current dependency is on the new .NET Standard DLL, which doesn't support v4.5.1. However, I believe I can work around it and will need to do some testing to ensure the new package is configured correctly.

Joe

**Comment by JoeMayo** [comment]
Tried to downgrade version. However, the project quickly ran into problems with version mismatches. Because of that, it's possible that I might get something to work on my machine that still might not work for you if versions don't match. Not sure I have the bandwidth right now for that. 

If you wanted to approach this, you could download the code and downgrade versions until you get the dll versions that match your project. One approach is to look at the *.csproj file histories for the version of LINQ to Twitter that you're using and update references to match that.

**Comment by nawidy** [comment]
Hi @JoeMayo,
I'm also having issues with upgrading to 5.0.0, coming from 5.0 beta 3
This is the error message that I see, have you seen this before?

MTOUCH: Error MT2001: Could not link assemblies. Reason: Error while processing references of 'App.iOS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' (MT2001) (App.iOS)

**Comment by nawidy** [comment]
Hi @JoeMayo have you seen this issue before that I have mentioned? do you recall your changes between 5.0 beta 3 and the 5.0 release?

**Comment by BrianARice** [comment]
I am getting this error: Could not install package 'linqtotwitter 5.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by JoeMayo** [comment]
Closing - This upgrade happened a while ago and sorry to the folks it affected.
