### ISSUE TITLE
Retire DestroyDirectMessageAsync

### ISSUE THREAD

**Issue by martani** [JoeMayo/LinqToTwitter#144]
I've been issuing calls to `DestroyDirectMessageAsync` and it's always failing with "Sorry, that page does not exist."
I thought v5.0.0 simply changes the underlying URL to Twitter to call to `direct_messages/events/destroy` but it seems there is a brand new function for that: `DeleteDirectMessageEventAsync`.

I think `DestroyDirectMessageAsync` should be deleted from v5.0.0 to avoid confusion.

**Comment by JoeMayo** [comment]
That's correct, you should use `...DirectMessageEvent` methods. 

The rationale is that when I added them to the beta months ago, the existing endpoints still worked and I named the new methods after the new endpoints. I also changed the return entity shape so that it's more in-line with what the Twitter API returns and avoids confusion between input properties and output results. e.g. various ids.

**Comment by martani** [comment]
The old API is completely shutdown by twitter now, so it makes sense to delete the code using those APIs.

**Comment by JoeMayo** [comment]
Agree, I'll deprecate them for a while so that I can show an error message to help folks that are migrating.

Joe

**Comment by VWGit** [comment]
Hi JoeMayo,
I am using the latest Library But i am getting error "Value cannot be null." on 
DirectMessageEvents.ToList()
Could you please explain how to call this method?

**Comment by JoeMayo** [comment]
@Git-Twitter That's documented at [Listing Direct Message Events](https://github.com/JoeMayo/LinqToTwitter/wiki/Listing-Direct-Message-Events).
