### ISSUE TITLE
Number of Tweets returned when Querying the Home Timeline

### ISSUE THREAD

**Issue by raulmarindev** [JoeMayo/LinqToTwitter#176]
Hello, I'm trying out LinqToTwitter and I have a doubt regarding the documentation for "[Querying the Home Timeline](https://github.com/JoeMayo/LinqToTwitter/wiki/Querying-the-Home-Timeline)". The documentation states that 

> The maximum number of tweets/retweets returned is 800

but then in the description of the Count parameter, it says 200 max. Is 800 the right value? Thank you in advance.

![image](https://user-images.githubusercontent.com/26367595/79509465-d4cf4280-803b-11ea-8a90-e4d3d9f907bb.png)

**Comment by JoeMayo** [comment]
If you look at the `Count `parameter, that means how many tweets are returned in one query. The 800 means that is the total number of tweets you can request in a window of time. For Home Timeline, the window is 15 minutes. To minimize requests, you would set `Count `to the max (200) and do 4 queries in a 15 minute window. 

Rather than paging, Twitter has a concept of working from the oldest tweet to the newest and you can see how to do that with the [Status Demo](https://github.com/JoeMayo/LinqToTwitter/blob/master/Samples/LinqToTwitter5/net48/CSharp/ConsoleSamples/StatusDemos.cs) code for an example of how to do that. I also have an older blog post on [Working with Timelines](http://geekswithblogs.net/WinAZ/archive/2012/09/02/working-with-timelines-with-linq-to-twitter.aspx), which follows the [Twitter Working with Timelines](https://developer.twitter.com/en/docs/tweets/timelines/guides/working-with-timelines) guidance.

**Comment by raulmarindev** [comment]
Thank you a lot for the explanation @JoeMayo.
