### ISSUE TITLE
Cannot upload image, Sorry, that page does not exist

### ISSUE THREAD

**Issue by apobekiaris** [JoeMayo/LinqToTwitter#180]
Hello,

I am looking for some feedback to what I am missing and cannot upload images while the mp4 works fine. 

My code is pretty much your samples

```cs
    var memoryCredentialStore = new InMemoryCredentialStore{
                ConsumerKey = ConsumerKey,
                ConsumerSecret = ConsumerSecret,
                OAuthToken = OAuthToken,
                OAuthTokenSecret = OAuthTokenSecret
            };
            var authorizer = new SingleUserAuthorizer{
                CredentialStore = memoryCredentialStore
            };
            await authorizer.AuthorizeAsync();
            var twitterCtx = new TwitterContext(authorizer);
            twitterCtx.Log=new StreamWriter(Console.OpenStandardOutput());
            var media = await twitterCtx.UploadMediaAsync(File.ReadAllBytes(Media.FullName), "image/png", "tweet_image");
            Media mediaStatusResponse = null;
            do{
                if (mediaStatusResponse != null){
                    var checkAfterSeconds = (int) mediaStatusResponse.ProcessingInfo?.CheckAfterSeconds;
                    WriteVerbose($"Twitter video testing in progress - waiting {checkAfterSeconds} seconds.");
                    await Task.Delay(checkAfterSeconds * 1000);
                }
                mediaStatusResponse = await twitterCtx.Media.Where(stat => stat.Type == MediaType.Status && stat.MediaID == media.MediaID)
                        .SingleOrDefaultAsync(); //Fails here 
            } while (mediaStatusResponse?.ProcessingInfo?.State == MediaProcessingInfo.InProgress);
```

```
Push-TwitterMedia -Media "C:\Users\Tolis\AppData\Local\Temp\test.jpeg"
--Log Starts Here--
Query:https://upload.twitter.com/1.1/media/upload.json
Method:PostMediaAsync
--Log Ends Here--
--Log Starts Here--
Query:https://upload.twitter.com/1.1/media/upload.json?command=STATUS&media_id=1253001089521266689
Method:QueryTwitterAsync
--Log Ends Here--
Push-TwitterMedia: Sorry, that page does not exist
```

I use the latest version.

**Comment by JoeMayo** [comment]
This took some investigation because I wasn't able to find specific documentation to explain this. Here's what I observed in the `Media `response after the upload:

	Image Response:

	{
		"media_id": 1253189667677069313,
		"media_id_string": "1253189667677069313",
		"media_key": "3_1253189667677069313",
		"size": 6917,
		"expires_after_secs": 86400,
		"image": {
			"image_type": "image/png",
			"w": 100,
			"h": 100
		}
	}

	Video Response:

	{
		"media_id": 1253190113615470593,
		"media_id_string": "1253190113615470593",
		"media_key": "7_1253190113615470593",
		"size": 284047,
		"expires_after_secs": 86400,
		"processing_info": {
			"state": "pending",
			"check_after_secs": 1
		}
	}

Notice that the Video Response has a `processing_info` property, which corresponds to the LINQ to Twitter `Media.ProcessingInfo` property. However, the Image Response doesn't. In LINQ to Twitter, the behavior is that the `Media.ProcessingInfo.Status` is `null `for Image, but `"pending"` for Video.

Therefore, I don't believe you need to check for status on images because there isn't `ProcessingInfo` that will allow you to wait. Another clue is the `404 NotFound`, indicating that images post immediately upon upload and you don't need to wait for success before tweeting - an intermediate processing state does not exist. However, because videos take longer, the additional status checks are necessary.

**Comment by apobekiaris** [comment]
thnks for the explanation I was just about to update my post cause I was able to post images after digging your samples.

You may want to consider updating your help files though to avoid such confusion as i used the original code from the wiki before digging the samples.

Great work whatsoever!

**Comment by JoeMayo** [comment]
Documented: [Uploading Images and Video](https://github.com/JoeMayo/LinqToTwitter/wiki/Uploading-Images-and-Video)
