### ISSUE TITLE
Media upload problem with vb.net

### ISSUE THREAD

**Issue by geziri** [JoeMayo/LinqToTwitter#203]
Hi,
I have trying to upload media but getting error :
System.Net.Http.HttpRequestException: 'An error occurred while sending the request.'

my code :
 Dim auth = New SingleUserAuthorizer With {
               .CredentialStore = New SingleUserInMemoryCredentialStore With {
                    .ConsumerKey = "********",
                     .ConsumerSecret = "*********",
                     .AccessToken = "*********",
                     .AccessTokenSecret = "*************"
               }
           }
        Dim context = New TwitterContext(auth)
        Dim uploadedMedia As Media = Await context.UploadMediaAsync(File.ReadAllBytes("C:\temp\aks.jpg"), "image/jpg", "tweet_image")
        Dim mediaIds = New List(Of ULong) From {
            uploadedMedia.MediaID
        }

 Await context.TweetAsync(" Hi, test ", mediaIds)

**Comment by JoeMayo** [comment]
Hi,

The error message you're showing doesn't provide a lot of information - just a generic "An error occurred...". So, there's no way to tell what the problem is. Normally, you'll see information from Twitter in the HTTP response with an error code and reason - can you post that?

Also, look at the Twitter API guidance on image specifications at [Media Best Practices](https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/uploading-media/media-best-practices).

[@JoeMayo](https://twitter.com/JoeMayo)

**Comment by geziri** [comment]
> Hi,
> 
> The error message you're showing doesn't provide a lot of information - just a generic "An error occurred...". So, there's no way to tell what the problem is. Normally, you'll see information from Twitter in the HTTP response with an error code and reason - can you post that?
> 
> Also, look at the Twitter API guidance on image specifications at [Media Best Practices](https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/uploading-media/media-best-practices).
> 
> [@JoeMayo](https://twitter.com/JoeMayo)

Hi
Thank you for reply,
I have fixed problem 
the issue from net framework 4.8 and i change to 4.5 is fixed
