### ISSUE TITLE
Custom exception message could be more clear

### ISSUE THREAD

**Issue by BillStrait** [JoeMayo/LinqToTwitter#215]
I'm getting an exception, the highlight is:

```
An unhandled exception occurred while processing the request.
TwitterQueryException: Request token missing - Please visit the LINQ to Twitter FAQ (at the HelpLink) for help on resolving this error.
LinqToTwitter.Net.TwitterErrorHandler.HandleUnauthorizedAsync(HttpResponseMessage msg)
```

I checked the faq in the wiki, I didn't see anything talking about 'Request token missing.' I haven't resolved the issue yet, but I'm guessing the first section around 401 errors will get me there.

**Comment by JoeMayo** [comment]
If you're able to repro and hit a breakpoint, there might be more info in the exception message. You're correct that if the status code is 401, which it sounds like it probably is, the 401 section of the FAQ can help.

**Comment by BillStrait** [comment]
The issue itself seems transient. It worked when I wrapped the call in a try/catch, and a few times after. Then it came back. I regenerated keys and it seems to have solved it? Oh well. It's something on my end for sure.

**Comment by JoeMayo** [comment]
What type of application are you building? e.g. ASP.NET

**Comment by BillStrait** [comment]
It is ASP.NET Core on .NET 5. It's been fine the last few attempts, I'm working on the callback method now, so if it comes back wonky I'll catch it as I'm building. 

Regenerating keys seems to have been the answer, they were copy/pasted to a few different places, so it's probable I had made a mistake there. Thank you though.

The issue I'm raising here is that the custom error message doesn't appear in the faq. After I wrap up I'd be happy to submit a change to the wiki.

**Comment by JoeMayo** [comment]
You might want to double check your session state to make sure it isn't InProc. The problem there is that the tokens are stored in the SessionStateCredentialCache. Since web servers recycle regularly, any InProc state is lost because it's held in memory rather than state service or SQL.

Contributions always welcome - I'll be deprecating the Wiki soon because documentation is now on GitHub Pages at https://www.linqtotwitter.com/ - it's on the gh-pages branch.
