### ISSUE TITLE
GetRequestTokenAsync does not load the TokenSecret credential

### ISSUE THREAD

**Issue by daxfohl** [JoeMayo/LinqToTwitter#28]
I'm trying to use this in Nancy web server, with distinct `myapp/api/twitter/request-auth` and `myapp/api/twitter/auth-callback` endpoints.  In `request-auth` I create the authorizer, add consumer key/secret to the creds, and call `GetRequestTokenAsync`.

Looking at the twitter docs and the raw http response, it appears this *should* return both a token and a token_secret.  However when the task is done, there's a `creds.OauthToken` but `creds.OauthTokenSecret` is still null.  I store these both in cookies.

From there I redirect to the twitter verifier URL, log in, and it redirects me back to `auth-callback`.  At this point I call `GetAccessTokenAsync` with the verifier and the four tokens, but it returns a 401 error presumably because the `OauthTokenSecret` is null.

I *think* this is a bug, but maybe I'm doing something wrong or have an incomplete understanding of OAuth.  However it appears that this is not useable in NancyFX.

**Comment by JoeMayo** [comment]
Hi daxfox,

You're using a lower level in the API, which is wrapped by higher level abstractions for authorization. These higher level abstractions implement IAuthorizer. e.g. WebAuthorizer, SingleAccessAuthorizer, or ApplicationOnlyAuthorizer. I haven't used NancyFX, but am sure there's a way to get this to work. Here's my documentation on Security and OAuth:

https://github.com/JoeMayo/LinqToTwitter/wiki/Securing-Your-Applications

An example is in a Web scenario, where you might use a WebAuthorizer and have user interaction. LINQ to Twitter sends the user to Twitter to authorize your app, the user authorizes, and Twitter sends the user back to your app to continue. This requires you to have a return URL so that Twitter knows where to send the user back to. To support this, WebAuthorizer has a BeginAuthorizeAsync and a CompleteAuthorizeAsync, where the Begin part passes a callback to the URL where you have the CompleteAuthorizeAsync logic. For more information on how this works, visit the WebAuthorizer documentation and browse the ASP.NET Web App demo code:

https://github.com/JoeMayo/LinqToTwitter/wiki/Implementing-OAuth-for-ASP.NET-Web-Forms

That user authorization process occurs the first time through and then you preserve credentials, like you are with the cookie. If you don't need the user in the middle, then look at SingleUserAuthorizer. Some endpoints also allow ApplicationOnlyAuthorizer, which gives you better rate limits. These authorizers assume that you have your own credentials, which you can get from your Twitter application page.

If the existing authorizers don't work for you, look at the underlying code for an authorizer closest to the Twitter OAuth you're trying to use and build your own IAuthorizer that L2T can consume. Also, (I'm unaware of how your code is calling L2T methods) remember that L2T is async, so you should await the Task returned by these async methods.

Joe

**Comment by daxfohl** [comment]
Hmm, I never was able to get it to work and so just wrote my own functions.  It'd be nice to have simple 

    static Task<Tuple<string, string, bool>> GetRequestToken(string consumerKey, string consumerSecret, string callbackUrl)

(where the returned strings are the request token/secret and the bool is oauth_callback_confirmed), and

    static Task<Tuple<string, string>> GetAccessToken(string consumerKey, string consumerSecret, string requestToken, string requestTokenSecret, string verifier)

exposed at the lowest levels, just so it's possible to get at those values directly if needed.

**Comment by JoeMayo** [comment]
I've been thinking for a while on doing a series on creating custom authorizers. For that, L2T will need a robust set of building blocks and your ideas are interesting.

**Comment by daxfohl** [comment]
My app was already in F#, so I found this unassuming little snippet http://blogs.msdn.com/b/lukeh/archive/2010/09/05/twitter-oauth-in-f.aspx, and updated `WebRequest` to `HttpClient` and changed `requestToken` and `accessToken` functions to async.  That in hand, I was able to do all the cookie/redirect stuff manually in nancy in a couple lines of code.  That got rid of the need for any "automagic" dependencies so I could fine-tune things as needed.
