### ISSUE TITLE
How to truly logout

### ISSUE THREAD

**Issue by ThaineNorris** [JoeMayo/LinqToTwitter#34]
I have a photo booth app that allows multiple photo booth guests to tweet their images to their own Twitter accounts. This app has been around for a while and used Linq2Twitter in its Windows 8.1 Windows Store app.

I need to be able to logout the current user so that a completely new user can log in. I cannot figure out how to do this in my new UWP app for Windows 10.

To logout the current user under Windows 8.1 I simply set the Authorizer to null and cleared the access token and access token secret values. This doesn't work under Windows 10. Instead when the next user tries to log in, the authorization dialog appears with the previous user's credentials and asks to authorize the app. In other words, the app is deauthorized but the user is not logged out.

How can this be done?

Thank you for this toolkit and for your help!

**Comment by JoeMayo** [comment]
Hi,

Those credentials are set after you first add them. LINQ to Twitter's UniversalAuthorizer uses the WebAuthenticationBroker class. The WebAuthenticationBroker displays a Web page, the Twitter Authentication page, in a customized browser. After you first add credentials, the WebAuthenticationBroker browser asks if you would like to save them. Your options are Yes and Skip. Pressing the Yes button will keep those credentials, but pressing Skip will make the page ask for new credentials each time. You can remove those credentials by visiting Control Panel/UserAccounts/Credential Manager. WebAuthenticationBroker doesn't offer an option to remove those credentials. 

I haven't searched to see if there is a Windows API that would remove those credentials from the Credentials Manager, but I would personally avoid that scenario because you're explicitly taking the user's choice away from them (e.g. what if a user complained that they keep selecting Yes to save credentials, but the credentials appear not to be saved - because your program is deleting them).

The Credential Manager scope is for the current user. If you log onto a different account on your computer, it will be a different credential set. If you run your app, as a different user, you'll see either blank credentials on the Twitter page, or the credentials for that user if that user chose the option to save credentials.

It sounds like your situation might be a development artifact. Think about the real-world scenario where you have different users using the same app. If they were using the same account, they would be operating in a less secure mode. Most users on the same machine will have their own accounts, which means they wouldn't encounter the problem with someone else's credentials appearing in their Twitter page. If they do indeed share the same account, they should remove the credentials, via the Credential Manager, and agree to press the Skip button when the browser asks them to save.

Joe
