### ISSUE TITLE
LinqToTwitter.Common.TwitterQueryException Unsupported Authentication, error on FullSearch 

### ISSUE THREAD

**Issue by rogerj007** [JoeMayo/LinqToTwitter#343]
Hi, trying to run a demo with the following code

https://github.com/JoeMayo/LinqToTwitter

Example
```

 return
                await
                    (from search in _twitterContext.TwitterSearch
                        where search.Type == SearchType.FullSearch &&
                              search.Query == searchTerm &&
                              search.TweetFields == TweetField.AllFieldsExceptPermissioned &&
                              search.Expansions == ExpansionField.AllTweetFields &&
                              search.MediaFields == MediaField.AllFieldsExceptPermissioned &&
                              search.PlaceFields == PlaceField.AllFields &&
                              search.PollFields == PollField.AllFields &&
                              search.UserFields == UserField.AllFields
                        select search)
                    .SingleOrDefaultAsync();
```

- .NET SDK version: 6.0
- LINQ To Twitter Version: 6.15
- Twitter API version (v1/v2)
- 

### Describe the issue
```
Stacktrace:
 An error occurred: LinqToTwitter.Common.TwitterQueryException Unsupported Authentication
   at LinqToTwitter.Net.TwitterErrorHandler.BuildAndThrowTwitterQueryException(String responseStr, HttpResponseMessage msg)
   at LinqToTwitter.Net.TwitterErrorHandler.HandleGenericErrorAsync(HttpResponseMessage msg)
   at LinqToTwitter.Net.TwitterErrorHandler.ThrowIfErrorAsync(HttpResponseMessage msg)
   at LinqToTwitter.Provider.TwitterExecute.HandleResponseAsync(HttpResponseMessage msg)
   at LinqToTwitter.Provider.TwitterExecute.QueryTwitterAsync[T](Request request, IRequestProcessor`1 reqProc)
   at LinqToTwitter.TwitterContext.ExecuteAsync[T](Expression expression, Boolean isEnumerable)
   at LinqToTwitter.Provider.TwitterQueryProvider.ExecuteAsync[TResult](Expression expression)
   at LinqToTwitter.TwitterExtensions.SingleOrDefaultAsync[T](IQueryable`1 query)
   at SM.MonitoreoTwitter.TwitterQuery.DoFullSearchAsync(String searchTerm) in 
```

**Comment by JoeMayo** [comment]
Hi,

This is an interesting scenario because with Twitter API v2 different endpoints require different authentication protocols. It's a transitional thing and we'll all have to navigate the waters until the Twitter API goes full OAuth 2. For your query, use the following Twitter docs for reference:

> https://developer.twitter.com/en/docs/twitter-api/tweets/search/api-reference/get-tweets-search-all

2 things here:

1. Notice that whoever uses the `FullSearch` endpoint must have Academic Access (educational institutions). Otherwise, your only option is [RecentSearch](https://www.linqtotwitter.com/LINQ-to-Twitter-6/Tweets/Recent-Search.html). The older `Search` option is a v1.1 endpoint and will eventually be scheduled for deprecation, so it's best to not build on that one.
2. The only authorizer you can use with this is OAuth 2 App Only, which LINQ to Twitter calls the `ApplicationOnlyAuthorizer`. You can find examples of all the authorizers, including `ApplicationOnlyAuthorizer` in the [Console demos](https://github.com/JoeMayo/LinqToTwitter/tree/main/Samples/LinqToTwitter6/Console/ConsoleDemo.CSharp).

Joe

**Comment by JoeMayo** [comment]
Closing - no response, so I don't know whether my suggestion resolved or some other issue.
