### ISSUE TITLE
May i use T2L 4 beta version in production

### ISSUE THREAD

**Issue by Timbioz** [JoeMayo/LinqToTwitter#40]
Hi! I started developing asp net 5 app. At the moment my webapp in developing stage and be ready after ~ 6-8 monthes.
May i start using L2T 4 beta now? And are there any advantages to use L2T beta or i should use old 3 version?
Thanks in advance!!! Merry Cristmas

**Comment by JoeMayo** [comment]
Here's the license:

https://github.com/JoeMayo/LinqToTwitter/blob/master/License.txt

I typically name something Beta to indicate that it may have more bugs than a non-beta version, which is consistent with standard practice. A stable release doesn't mean that the software doesn't have bugs, because all software has bugs, but it means that it meets my subjective judgement of being better than Beta. I would like to see folks use the Beta so they can provide feedback and let me know if there are any bugs. You always have the option of falling back to v3.x if that would make you more comfortable. The exception is that v4.0 is the only available option for Windows 10 development, but since you're building an ASP.NET app it doesn't apply to your situation. Right now, all of the new features are going into LINQ to Twitter v4.0 Beta.

**Comment by Timbioz** [comment]
Thanks for reply! And another question about beta version... Wich method i need to use instead MvcAuthorizer in Beta version that grants me OAuth with all access to Twitter API
Sorry for bad English

**Comment by JoeMayo** [comment]
There's a SingleUserAuthorizer that works if you have all 4 credentials filled in - you can find the AccessToken and AccessTokenSecret in the Twitter application page.

I'll also mention ApplicationOnlyAuthorizer, though I only works for certain endpoints (that require user context). However, it does provide a higher rate limit.

I have more info on authorizers at https://github.com/JoeMayo/LinqToTwitter/wiki/Securing-Your-Applications
