### ISSUE TITLE
INotifyPropertyChanged Implementation

### ISSUE THREAD

**Issue by HassanElZarkawy** [JoeMayo/LinqToTwitter#43]
Is there any way to implement INotifyPropertyChanged to the base classes such as Status?

**Comment by JoeMayo** [comment]
Hi,

I recall being asked this a couple times. Apparently, there are other libraries that have made their objects INotifyPropertyChanged too. I can see where this request comes from because it would be a way to reduce the amount of code that users have to write. However, here are some reasons why it might not be as good an idea as intended:

1. INotifyPropertyChanged assumes a XAML technology client. LINQ to Twitter supports other technologies like ASP.NET, Azure, and many more .NET development scenarios.
2. INotifyPropertyChanged assumes users don't have a 3rd party MVVM framework, where their objects derive from a base class that provides this interface, along with implementation. It's unlikely to support the associated conventions of a given framework either.
3. From a design perspective, turning a data entity into a view model might not be appropriate. The LINQ to Twitter entities contain all of the data returned from the Twitter API. This data is nested to several levels in some cases (e.g. ExtendedEntites on a Status). Typically, a View Model takes on a shape that supports one or more views, other than the shape of the raw data - essentially exposing your data model in your view. This would also be a heavyweight option for binding data to a view.
4. Binding the data model is also semantically less intuitive. e.g. because an entity like Status uses ScreenName as an input, the LINQ to Twitter convention is to name matching outputs with a "Response" suffix, like ScreenNameResponse. I'm not sure that's 100% meaningful in the view. It also makes the developer have to reason about the data model and view (mixed paradigms) in the view itself where UX should be the main consideration.

I typically find it more desirable to build custom view models with naming conventions and shapes that support my views and work naturally with the MVVM framework library I'm using on a project. If you're familiar with the MVVM framework (if used), view models match the application intention and view design, and the mapping between LINQ to Twitter entity to view model shows the data flow (in a separate function/layer/component), the code might be easier to maintain.

Joe
