### ISSUE TITLE
Simple User where query by ScreenName causes exception

### ISSUE THREAD

**Issue by BrianVallelunga** [JoeMayo/LinqToTwitter#68]
This simple query throw an exception instead of returning null:

```
var twitterUser = twitterContext.User
           .Where(u => u.Type == UserType.Show && u.ScreenName == screenName)
           .SingleOrDefault();
```

The exception details are:

System.AggregateException: One or more errors occurred. ---> LinqToTwitter.TwitterQueryException: User not found.
   at LinqToTwitter.Net.TwitterErrorHandler.BuildAndThrowTwitterQueryException(String responseStr, HttpResponseMessage msg)
   at LinqToTwitter.Net.TwitterErrorHandler.<HandleGenericErrorAsync>d__1.MoveNext()...

I'm not sure what could be more simple. Am I doing something wrong? This is with the latest stable version of the library from Nuget.

**Comment by JoeMayo** [comment]
LINQ to Twitter is async. Try this:

    var twitterUser = await twitterContext.User
           .Where(u => u.Type == UserType.Show && u.ScreenName == screenName)
           .SingleOrDefaultAsync();

[@JoeMayo](https://twitter.com/JoeMayo)

**Comment by BrianVallelunga** [comment]
Shouldn't both the Async and Non-Async methods work though? And anyway, switching to the following code produces the same results:

var twitterUserTask = twitterContext.User.Where(u => u.Type == UserType.Show && u.ScreenName == "ascreennamethatdoesntexist").SingleOrDefaultAsync();
twitterUserTask.Wait();

I think there's something fundamentally wrong with the provider not catching the API response error and returning a null result.

**Comment by JoeMayo** [comment]
Starting with LINQ to Twitter 3.x, I made the library async only. A few people lament the old synchronous library, v2.x, which is still available, but async feedback seems to be well-received by most developers. There's a lot of material on the benefits of async if you would like to search and do some research. Steven Cleary's blog is an excellent resource: http://blog.stephencleary.com/. 

On the Wait() call, while I've made a point to ensure the library calls ConfigureAwait(false) to avoid deadlocks, using Wait() isn't recommended as it has the potential to lock your app on the UI thread. Using async/await is the preferred option.

Looking closer at the exception, it say's what the problem is:

    LinqToTwitter.TwitterQueryException: User not found.

I wrap errors from Twitter in a TwitterQueryException and use Twitter's error message. Sometimes you can look inside the exception for more info. The ErrorCode and ReasonPhrase are from the Twitter message contents and the StatusCode is the HTTP status code from the Twitter response.

I believe that returning an exception is more appropriate. An exception represents the fact that the method could not perform it's intended purpose. That's true in this case because the query was not able to return a timeline for the user. Some would say that returning null from a method is not a good practice because it leads to null reference exceptions. You'll find a consistent pattern in LINQ to Twitter that I try to return an empty object whenever I don't have data to fill in for that object. Of course there are so many levels deep you can go. There's always a tradeoff to be had, but I don't believe returning null leads to productivity.

[@JoeMayo](https://twitter.com/JoeMayo)
