### ISSUE TITLE
Where is my Twitter oauthToken and oauthTokenSecret?

### ISSUE THREAD

**Issue by HerrimanCoder** [JoeMayo/LinqToTwitter#86]
I have just created a Twitter "App" for a simplistic conference demo in which my software tool is supposed to do a post to Twitter programmatically via dotnet. I was easily able to locate my Consumer Key (API Key), Consumer Secret (API Secret), accessToken and accessTokenSecret here:

> https://apps.twitter.com/app/xxxxx/keys

But LinqToTwitter also [apparently] requires an oauthToken and oauthTokenSecret which I cannot find anywhere in my Twitter app settings or account settings. Where can I find these two values?

Note: When I try to run a simple LinqToTwitter demo function without populating  oauthToken and oauthTokenSecret I get an unhandled exception:

> Unable to verify your credentials.

Any ideas?

**Comment by HerrimanCoder** [comment]
I found some sample c# code that works great and those 2 add'l keys were completely unnecessary.

**Comment by Vitae666** [comment]
Be great to know that C# code :)

**Comment by JoeMayo** [comment]
@Vitae666 Not sure what OP was talking about because LINQ to Twitter has, for years, supported every form of authentication that the Twitter API provides. Here are some resources to explain:

Here are examples of PIN, Application Only, and Single User authorization:

[Console Samples Demo Code](https://github.com/JoeMayo/LinqToTwitter/blob/master/Samples/LinqToTwitter5/net48/CSharp/ConsoleSamples/Program.cs)

If you look at all of the samples in the source code, you'll find demos for Web Forms, MVC, and Xamarin.

Here's where the use of those are documented:

[Wiki Documentation](https://github.com/JoeMayo/LinqToTwitter/wiki/Securing-Your-Applications)

Is that what you're asking?

[@JoeMayo](https://twitter.com/joemayo)
