### ISSUE TITLE
Since parameter is not available not SinceID

### ISSUE THREAD

**Issue by seansparkman** [JoeMayo/LinqToTwitter#87]
There is a parameter for since like until, but it's all the tweets since date X.

> superhero since:2015-12-21	containing “superhero” and sent since date “2015-12-21” (year-month-day).
[https://dev.twitter.com/rest/public/search](https://dev.twitter.com/rest/public/search)

**Comment by seansparkman** [comment]
Going to create a new pull request with the fix for PCL as well.

**Comment by JoeMayo** [comment]
Sean, I appreciate the pull request, but am not sure about the `since ` parameter. With the Search API, there are two types of parameters: Query Operators and Query String Parameters.

As you noted, Query Operators appear at (https://dev.twitter.com/rest/public/search). Those are part of the query text. e.g. assigned to the LINQ to Twitter 'ctx.Query == xyx' parameter, which maps to the Twitter API 'q' parameter.

While I do see a 'since_id' Query String Parameter at (https://dev.twitter.com/rest/reference/get/search/tweets", I don't see a 'since'. I do see the 'until' which is a LINQ to Twitter parameter.

Are you seeing something different?

Note: There was a time when I supported Query Operators as normal parameters, but people had a lot of trouble with them. e.g. Since they were part of the 'q' parameter, they would make the query more complex and longer, resulting in Twitter frequently returning complexity errors. I figured that removing the parameters and letting developers explicitly format those operators in the Query parameter/property would make it more explicit that their queries were too complex for Twitter to figure out. Essentially, the Twitter Search API is brittle and not full featured. So, like you, I thought it was a good idea, but the amount of support required to answer questions on errors I have no control over made me think otherwise.
